config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :evil_artifacts do
    collection do
      get "/category/:category", to: "evil_artifacts#artifacts_of_a_category", as: 'artifacts_of_a_category'
    end
    resources :orders, only: [:new, :create, :update]
  end
  resources :orders, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evil_artifact.rb
class EvilArtifact < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_many :users, through: :orders
  has_many_attached :photos

  CATEGORIES = ['Poison', 'Fire Guns', 'Meele Weapon', 'Hallucinogenic', 'Explosives', 'Pull or Prank'].freeze
  VERSATILITY = ['One-Handed', 'Two-Handed']
  validates :name, :description, :price, :category, presence: true
  validates :description, length: { minimum: 10 }
  validates :lethality, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :price, numericality: { only_float: true }
  validates :category, inclusion: { in: CATEGORIES }
  validates :versatility, inclusion: { in: VERSATILITY }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :evil_artifact

  validates :quantity, presence: true

  def total
    evil_artifact.price * quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :evil_artifacts
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :codename, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:codename, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:codename, :photo])
  end
end

app/controllers/evil_artifacts_controller.rb
class EvilArtifactsController < ApplicationController
  def index
    @evil_categories = EvilArtifact::CATEGORIES
  end

  def artifacts_of_a_category
    @evil_artifacts = EvilArtifact.where(category: params[:category])
  end

  def show
    @evil_artifact = EvilArtifact.find(params[:id])
  end

  def new
    @evil_artifact = EvilArtifact.new
  end

  def create
    @evil_artifact = EvilArtifact.new(evil_artifact_params)
    @evil_artifact.user = current_user
    if @evil_artifact.save
      redirect_to evil_artifact_path(@evil_artifact), notice: 'Evil artifact was successfully created.'
    else
      render :new
    end
  end

  def edit
    @evil_artifact = EvilArtifact.find(params[:id])
  end

  def update
    @evil_artifact = EvilArtifact.find(params[:id])
    if @evil_artifact.user == current_user
      @evil_artifact.update(evil_artifact_params)
      flash[:notice] = 'Updated!'
    else
      flash[:notice] = 'Not authorized!'
    end
    redirect_to evil_artifact_path(@evil_artifact)
  end

  def destroy
    @evil_artifact = EvilArtifact.find(params[:id])
    @evil_artifact.destroy if @evil_artifact.user == current_user
    redirect_to evil_artifacts_path
  end

  private

  def evil_artifact_params
    params.require(:evil_artifact).permit(:name, :description, :price, :category, :lethality, :reach, :versatility, photos: [])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @evil_artifact = EvilArtifact.find(params[:evil_artifact_id])
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    evil_artifact = EvilArtifact.find(params[:evil_artifact_id])
    @order.evil_artifact = evil_artifact
    if @order.save
      redirect_to order_path(@order)
    else
      redirect_to evil_artifact_path(@order.evil_artifact)
    end
  end

  def update
  end

  private

  def order_params
    params.require(:order).permit(:quantity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    redirect_to evil_artifacts_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_image_helper.rb
module CategoriesImageHelper
  def category_image(category)
    case category
    when 'Poison'
      "https://cryptobotanicalfindings.files.wordpress.com/2011/11/poison-ivy.jpg"
    when 'Fire Guns'
      "https://pro2-bar-s3-cdn-cf6.myportfolio.com/561f892815925c323fbf4261410bb1ec/006157d1-4c43-4c45-a419-9c948d27420d_rw_1200.jpg?h=e071d579976bb74c883858e8d7cbcd04"
    when 'Meele Weapon'
      "https://i.redd.it/oggzwfdev5g41.jpg"
    when 'Explosives'
      "https://dcn-wp.s3.us-west-1.amazonaws.com/wp-content/uploads/2014/07/04155717/secret-origins-4-harley-quinn-cover.png"
    when 'Hallucinogenic'
      "https://cdn.staticneo.com/w/batman/thumb/ScaryGas.jpg/300px-ScaryGas.jpg"
    when 'Pull or Prank'
      "https://pm1.narvii.com/6336/6cdf704f958612dd5f2c678e1c6d7401327b403c_hq.jpg"
    end
  end
end

app/helpers/category_background_helper.rb
module CategoryBackgroundHelper
  def background_url(category)
    case category
    when 'Pull or Prank'
      'https://static1.srcdn.com/wordpress/wp-content/uploads/Batman-vs-The-Joker-in-The-Killing-Joke.png?q=50&fit=crop&w=960&h=500&dpr=1.5'
    when 'Poison'
      'https://c4.wallpaperflare.com/wallpaper/967/767/746/comics-birds-of-prey-bodysuit-brown-hair-wallpaper-preview.jpg'
    when 'Meele Weapon'
      'https://cdn.wallpapersafari.com/37/87/MLIqOP.jpg'
    when 'Explosives'
      'https://images3.alphacoders.com/587/587233.jpg'
    when 'Fire Guns'
      'https://kanto.legiaodosherois.com.br/w760-h398-cfill/wp-content/uploads/2020/09/legiao_WjkySMHFL83Z.jpg.jpeg'
    when 'Hallucinogenic'
      'https://fictionhorizon.com/wp-content/uploads/2020/12/robins-hallucinations-from-the-fear-toxin-new-52-1.jpg'
    end
  end
end

app/views/evil_artifacts/artifacts_of_a_category.html.erb
<div class="position-relative">
  <div class="banner category" style="background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.6)), url(<%= asset_path(background_url(params[:category]))%>); background-size: contain;">
  <h1 class="text-white"><%= params[:category] %></h1>
</div>
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <% @evil_artifacts.each do |artifact| %>
        <div class="card-product justify-content-between mb-4">
          <%= artifact.photos.empty? ? (image_tag 'poison_product.jpg') : (cl_image_tag artifact.photos.first.key) %>
            <div class="card-product-infos">
              <%= link_to evil_artifact_path(artifact), class:'text-decoration-none' do %>
                <h2><%= artifact.name %></h2>
                <p><%= "Sold by #{artifact.user.codename}" %><p>
              <% end %>
            </div>
            <div class="vilan-user">
              <% if artifact.user.photo.attached? %>
                <%= cl_image_tag artifact.user.photo.key, id: "avatar-card" %>
              <% else %>
                <%= image_tag "joker_user.jpg", id: "avatar-card" %>
              <% end %>
              <p><%= "US$ #{artifact.price}" %><p>
            </div>
        </div>
      <% end %>
    <%= link_to 'Back', evil_artifacts_path, class:'btn btn-red mt-3' %>
  </div>
</div>

app/views/evil_artifacts/edit.html.erb
<div class="cover-forms d-flex justify-content-center align-items-center">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-6">
        <div class="box-forms my-3 p-3">
  <h1>Edit an existing Evil Artifact</h1>
  <%= simple_form_for(@evil_artifact) do |f| %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :name %>
    <%= f.input :lethality %>
    <%= f.input :reach %>
    <%= f.input :versatility %>
    <%= f.input :description %>
    <%= f.input :category, collection: EvilArtifact::CATEGORIES %>
    <%= f.input :price %>
    <%= f.submit 'Edit' %>
  <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/evil_artifacts/index.html.erb
<div class="position-relative">
  <div class="banner" style="background-image: url(<%= asset_path('https://static3.cbrimages.com/wordpress/wp-content/uploads/2019/06/Batman-vs-Thomas-Wayne-Batman-from-DC-comics.jpg?q=50&fit=crop&w=960&h=500&dpr=1.5')%>)">

      <span id="banner-typed-text"></span>

</div>

<div class="container my-5">
  <div class="d-flex justify-content-end">
    <%= link_to 'I want to sell', new_evil_artifact_path, class: 'btn btn-red mb-5' %>
  </div>
  <div class="owl-carousel">
    <% @evil_categories.each do |category| %>
      <div class="card card-carousel">
        <%= image_tag category_image(category), style: "height: 20rem" %>
        <div class="card-body text-center card-carousel-body">
          <%= link_to category, artifacts_of_a_category_evil_artifacts_path(category) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/evil_artifacts/new.html.erb
<div class="cover-forms d-flex justify-content-center align-items-center">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-6">
        <div class="box-forms my-3 p-3">
          <h1>Create an Evil Artifact</h1>
          <%= simple_form_for(@evil_artifact) do |f| %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.input :name %>
          <%= f.input :lethality, collection: [0, 1, 2, 3, 4, 5] %>
          <%= f.input :reach %>
          <%= f.input :versatility, collection: EvilArtifact::VERSATILITY %>
          <%= f.input :description %>
          <%= f.input :category, collection: EvilArtifact::CATEGORIES %>
          <%= f.input :price %>
          <%= f.submit 'Create', class:"btn btn-red mt-2" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/evil_artifacts/show.html.erb
<div class="product-show-container">
  <div class="product-show-center-container">
    <h2 class="my-4"><%= "#{@evil_artifact.name}" %></h2>
    <div class="px-4">
      <% @evil_artifact.photos.each do |photo| %>
        <%= cl_image_tag photo.key, height: 350, width: 250, crop: :fill, class:"mx-4" %>
      <% end %>
    </div>
  </div>

  <div class="my-5 product-show">
    <div class="card card-product-show mx-5">
        <h5 class="card-header card-order-header"> <strong>Product Informations</strong> </h5>
        <div class="card-body card-order-body">
          <h5 class="card-title"><%= @evil_artifact.description %></h5>
          <p class="card-text"> <strong>Category:</strong> <%= @evil_artifact.category %></p>
          <p class="card-text"> <strong>Sold by:</strong> <%= @evil_artifact.user.codename %></p>
          <p class="card-text"> <strong>Price:</strong> US$ <%= @evil_artifact.price %></p>
          <p class="card-text"> <strong>Lethality:</strong> <%= @evil_artifact.lethality %><p>
          <p class="card-text">  <strong>Reach:</strong> <%= @evil_artifact.reach  %> ft<p>
          <p class="card-text"> <strong>Versatility:</strong> <%= @evil_artifact.versatility %><p>
          <%= link_to 'Buy', new_evil_artifact_order_path(@evil_artifact), class: 'btn btn-red float-right' %>
          <% if current_user == @evil_artifact.user %>
            <%= link_to 'Edit an artifact',  edit_evil_artifact_path(@evil_artifact), class: 'btn btn-red mr-3' %>
            <%= link_to 'Detete this artifact', evil_artifact_path(@evil_artifact), method: :delete, class: 'btn btn-red', data: { confirm: 'Are you sure you want to delete this item?' } %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArkhamBlackMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="bcolor">
    <%# Do not show navbar for homepage %>
    <% unless params[:action] == 'home' || (['devise/registrations', 'devise/sessions', 'devise/passwords'].include? params[:controller]) %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/orders/new.html.erb
<div class="order-container">
  <div class="left-container-new-order", style="background-image: url('<%= @evil_artifact.photos.empty? ? (image_url 'poison_product.jpg') : (cl_image_path @evil_artifact.photos.first.key) %>')">
  </div>
  <div class="right-container-new-order">
    <h2 class="text-center my-5">CONFIRM YOUR ORDER</h2>
      <div class="card card-order mx-5">
        <h5 class="card-header card-order-header"><%= @evil_artifact.name %></h5>
        <div class="card-body card-order-body">
          <h5 class="card-title"><%= @evil_artifact.description %></h5>
          <p class="card-text">Sold by: <%= @evil_artifact.user.codename %></p>
          <p class="card-text">Unit price: US$ <%= @evil_artifact.price.round(2)%></p>
          <%= simple_form_for ([@evil_artifact, @order]) do |f| %>
            <%= f.input :quantity, placeholder: 'nº of itens' %>
            <%= f.submit 'Confirm', class:'btn btn-red mt-2' %>
            <%= link_to 'Cancel', evil_artifacts_path, class: 'btn btn-red mt-2 float-right' %>
          <% end %>
        </div>
      </div>
  </div>
</div>

<%# COLOCAR BOTÃO DE BACK! %>

app/views/orders/show.html.erb
<div class="show-order-container">
  <div class="left-container-show-order">
  </div>
  <div class="right-container-show-order">
    <h2 class="text-center mb-5">ORDER CONFIRMED</h2>
      <div class="card card-order mx-5">
        <h5 class="card-header card-order-header"><strong><%= @order.evil_artifact.name %></strong></h5>
        <div class="card-body card-order-body">
          <h5 class="card-title"><%= @order.evil_artifact.description %></h5>
          <p class="card-text"><strong>Sold by:</strong> <%= @order.evil_artifact.user.codename %></p>
          <p class="card-text"><strong>Unit price:</strong> US$ <%= @order.evil_artifact.price.round(2) %></p>
          <p class="card-text"><strong>Quantity:</strong> <%= @order.quantity %></p>
          <p class="card-text"><strong>Total Price:</strong> <%= @order.total.round(2) %></p>
        </div>
      </div>
      <div class="goodbye mt-5">
        <span id="goodbye-message"></span>
      </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="cover d-flex justify-content-center align-items-center" style="background-image: url(<%= asset_path('home_background_image.jpg')%>)">
  <div class="d-flex  justify-content-start align-items-center flex-grow-1 mx-4">
    <div class="left-container">
      <h1>Arkham Black Market</h1>
      <p>
        The best products for the nastiest intentions
      </p>
      <%= link_to 'Alliance', new_user_registration_path, class:"btn btn-ghost" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to evil_artifacts_path, class: "navbar-brand" do %>
    <div class="navbar-brand">
      <%= image_tag "logo.png" %>
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active ">
          <%= link_to "Home", evil_artifacts_path, class: "nav-link text-red mr-1 mt-1" %>
        </li>
        <li class="nav-item ">
          <%= link_to "Sell", new_evil_artifact_path, class: "nav-link text-red mr-2 mt-1" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "avatar-card", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "joker_user.jpg", class: "avatar dropdown-toggle", id: "avatar-card", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="avatar-card">
            <%# <%= link_to "Change password", edit_user_password_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>

        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>